name = "Advent-Of-Code-2024"
version = "0.1.0"
defaultTargets = ["advent-of-code-2024"]

[[lean_exe]]
name = "Day1"
srcDir="AdventOfCode2024"
root = "Day1"

[[lean_exe]]
name = "Day2"
srcDir="AdventOfCode2024"
root = "Day2"

[[lean_exe]]
name = "Day3"
srcDir="AdventOfCode2024"
root = "Day3"

[[lean_exe]]
name = "Day4"
srcDir="AdventOfCode2024"
root = "Day4"

[[lean_exe]]
name = "Day5"
srcDir="AdventOfCode2024"
root = "Day5"

[[lean_exe]]
name = "Day6"
srcDir="AdventOfCode2024"
root = "Day6"